export const COLONY_SETTINGS: ColonySettings = {
    expeditionTargets: [''],
    pioneerTarget: '',
    breakerTarget: { room: 'E59S59', id: '690d88caa530f0e7ef6ff26f' },
    defendRoom: '',
    salvageRoom: '', // Leave empty to salvage in the home room, or set a target room string
    salvageContainers: false,
    salvageEnergy: false,
    depositHome: true,
    remoteBuild: '',
    claimRoom: '',
    ignoredSources: ['none'],
    //dismantle targets and wall/rampart attack settings
    dismantleTargets: {
        "E59S59": '690d88caa530f0e7ef6ff26f'
    },
    attackWalls: false,
    attackRamparts: false,
    //wall and rampart repair settings
    roomWallMaxHits: {
        "E59S58": 25e4,
        "E58S58": 1e5,
        "E58S57": 1e5,
        "E57S57": 1e5,
        "E55S58": 1e5,
        "E59S55": 1e5
    },
    roomRampartMaxHits: {
        "E59S58": 1e5,
        "E58S58": 1e4,
        "E58S57": 1e5,
        "E57S57": 1e4,
        "E55S58": 1e4,
        "E59S55": 1e5
    },
    remoteMining: {
        'E58S57': ['E58S56', 'E5S56'], // Example: 'HomeRoom': ['RemoteRoom1', 'RemoteRoom2']
    },
    mineralQuotas: {
        'E59S58': 10000,
        "E55S58": 1e5
    },
    resourceTransfers: [
        { sourceRoom: 'E58S56', destRoom: 'E58S57', resource: RESOURCE_POWER, count: 2 }
        // Options: RESOURCE_ENERGY, RESOURCE_POWER, RESOURCE_POWER, RESOURCE_HYDROGEN, RESOURCE_OXYGEN, RESOURCE_UTRIUM, RESOURCE_LEMERGIUM, RESOURCE_KEANIUM, RESOURCE_ZYNTHIUM, RESOURCE_CATALYST, RESOURCE_GHODIUM
    ],
    terminalTransfers: {
        // Example: 'E58S59': [{ resource: RESOURCE_ENERGY, amount: 50000 }, { resource: RESOURCE_OXYGEN, amount: 1000 }]
    },
    debug: false,
    roomQuotas: {
        "E55S58": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 1,
            marketHauler: 0,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 0,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        "E57S56": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 2,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        "E57S57": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 1,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        "E58S56": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 2,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        "E58S57": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 1,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        "E58S58": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 2,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        "E58S59": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 1,
            marketHauler: 0,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        "E59S55": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 2,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        },
        /*
        "E59S56": {
            remoteMiner: 0,
            remoteHauler: 0,
            remoteRepairer: 0
        },
        "E59S57": {
            remoteMiner: 0,
            remoteHauler: 0,
            remoteRepairer: 0
        },
        */
        "E59S58": {
            defender: 0,
            miner: 2,
            dismantleMiner: 0,
            extractorMiner: 0,
            hauler: 1,
            upgradeHauler: 0,
            upgrader: 1,
            builder: 0,
            repairer: 1,
            salvager: 0,
            transferHauler: 0,
            remoteMiner: 0,
            remoteHauler: 0,
            remoteExtractorMiner: 0,
            pioneer: 0,
            expedition: 0,
            vanguard: 0,
            breaker: 0,
            remoteBuilder: 0,
            claimer: 0
        }
    }
};
